export const ActionTypes = {
  CHANGE_SEARCH_FIELD : 'CHANGE_SEARCH_FIELD',
  FETCH_ROBOTS_START : 'FETCH_ROBOTS_START',
  FETCH_ROBOTS_SUCCESS : 'FETCH_ROBOTS_SUCCESS',
  FETCH_ROBOTS_FAILURE : 'FETCH_ROBOTS_FAILURE'
};
